### ISSUE TITLE
How to add values international mode

### ISSUE THREAD

**Issue by webserveis** [llollox/CompoundButtonGroup#1]
interesting component, but if you have an application with more languages, as you can add entries to their will translate, but without changing internal value

```
label/value
house=>house
casa=>house
```
if you find it interesting, could allow entering optimal HashMap
`HashMap<String,String>`

**Comment by llollox** [comment]
I've just release the new version 1.0.2. of my library.
In this new version I've added the support for `Hashmap<String, String>` to set the entries.
I've changed also the `OnButtonSelectedListener` that now has a method with the following signature:

`void onButtonSelected(int position, String value, boolean isChecked);
`
Substantially, I've added the value of the button clicked into the arguments.

All the changes are written in details into the documentation.
Hopefully, this would solve your issue.
